urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'franks_electronics.views.home', name='home'),
    # url(r'^franks_electronics/', include('franks_electronics.foo.urls')),
    url(r'^$', 'tickets.views.index'),
    url(r'^tickets/search/', 'tickets.views.search'),
    url(r'^tickets/number/(?P<number>\d+)/$', 'tickets.views.number'),
    url(r'^tickets/voice/$', 'tickets.views.voice'),
    url(r'^tickets/id/(?P<ticket_id>\d+)/$', 'tickets.views.detail'),

    url(r'^services/$', 'django.views.generic.simple.direct_to_template', {'template': 'tickets/services.html'}),
    url(r'^about/$', 'django.views.generic.simple.direct_to_template', {'template': 'tickets/about.html'}),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

tickets/models.py
from django.db import models
from django.db.models.signals import post_save
from decimal import Decimal

class CurrencyField(models.DecimalField):
    __metaclass__ = models.SubfieldBase

    def to_python(self, value):
        try:
            return super(CurrencyField, self).to_python(value).quantize(Decimal("0.01"))
        except AttributeError:
            return None

STATUS_DETAIL = (
    ('C', 'Created', 'The ticket has been created but has not been entered into the estimate queue.'),
    ('I', 'In estimate queue', 'The item has been signed in and is currently in queue for the issue to be diagnosed and an estimate to be created.'),
    ('E', 'On bench for estimate', 'The item is on the bench and the issue is being diagnosed. Repair parts are being researched and an estimate is being created.'),
    ('T', 'To be called', 'The estimate of the repair has been completed and a phone call has been scheduled. You should recieve a phone call today.'),
    ('W', 'Waiting for estimate approval', 'The estimate of the repair has been completed and the customer has been called. We are currently awaiting for an approval for repair.'),
    ('Q', 'In repair queue', 'The estimate has been approved by the customer and parts are on order. The item is in queue to be repaired when parts arrive.'),
    ('R', 'On bench for repair', 'The item is on the bench and the issue is being repaired.'),
    ('B', 'Burn in', 'The item has been repaired and is going through rigorous testing.'),
    ('U', 'To be picked up', 'The item is ready to be picked up.'),
    ('L', 'Closed', 'The item has been picked up and the repair ticket has been closed.'),
)

STATUS_CHOICES = tuple(x[0:2] for x in STATUS_DETAIL)

class Ticket(models.Model):
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=True)
    number = models.IntegerField()
    customer = models.CharField(max_length=128, blank=True)
    make = models.CharField(max_length=255, blank=True, verbose_name="Item make")
    model = models.CharField(max_length=255, blank=True, verbose_name="Item model")
    serial_number = models.CharField(max_length=255, blank=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='S')
    notes = models.TextField(blank=True)
    private_notes = models.TextField(blank=True)
    #estimate = models.DecimalField(null=True, decimal_places=2, max_digits=16)
    estimate = CurrencyField(blank=True, null=True, decimal_places=2, max_digits=16)
    estimate_date = models.DateField(blank=True, null=True)
    approved = models.BooleanField(verbose_name="Estimate approved")
    approval_date = models.DateField(blank=True, null=True)
    completion_date = models.DateField(blank=True, null=True)

    @property
    def status_detail(self):
        for detail in STATUS_DETAIL:
            if detail[0] == self.status:
                return detail[2]
        return ''

    @property
    def estimate_display(self):
        result = self.estimate
        return "$%s" % result if result else ''

    @property
    def estimate_date_display(self):
        result = self.estimate_date
        return result if result else ''

    @property
    def approved_display(self):
        return 'Yes' if self.approved else ''

    @property
    def approval_date_display(self):
        result = self.approval_date
        return result if result else ''

    @property
    def completion_date_display(self):
        result = self.completion_date
        return result if result else ''

    def latest_status_log(self):
        try:
            return StatusLog.objects.filter(ticket=self).latest()
        except StatusLog.DoesNotExist:
            return None

    def log_status(self):
        lastlog = self.latest_status_log()
        if lastlog is None or lastlog.status != self.status:
            newlog = StatusLog(ticket=self)
            newlog.status = self.status
            newlog.save()

    def get_absolute_url(self):
        return "/tickets/id/%i/" % self.id

    def save(self, *args, **kwargs):
        super(Ticket, self).save(*args, **kwargs)
        self.log_status()

    def __unicode__(self):
        return "Ticket #%d" % self.number
        
    class Meta:
        ordering = ['-timestamp']
        verbose_name = "service ticket"
        verbose_name_plural = "service tickets"

class ContactLog(models.Model):
    ticket = models.ForeignKey(Ticket)
    timestamp = models.DateTimeField()
    status = models.TextField()

    def __unicode__(self):
        return self.status

    class Meta:
        ordering = ['ticket', '-timestamp']
        verbose_name = "customer contact history"
        verbose_name_plural = "customer contact history"
        get_latest_by = 'timestamp'

class StatusLog(models.Model):
    ticket = models.ForeignKey(Ticket)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='S')

    def __unicode__(self):
        return "Ticket #%d status log at %s" % (self.ticket.number, str(self.timestamp))

    class Meta:
        ordering = ['ticket', '-timestamp']
        verbose_name = "ticket status history"
        verbose_name_plural = "ticket status history"
        get_latest_by = 'timestamp'

tickets/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response, redirect, get_object_or_404
from tickets.models import Ticket
from django import forms
from django.utils.translation import ugettext as _
from django.conf import settings
from django.template import RequestContext

class SearchForm(forms.Form):
    number = forms.IntegerField(min_value=1)

    def clean_number(self):
        n = self.cleaned_data['number']
        try:
            self.cleaned_data['ticket'] = Ticket.objects.get(number=n)
        except Ticket.DoesNotExist:
            raise forms.ValidationError("Ticket #%d could not be found." % n)

def index(request):
    return render_to_response('tickets/index.html', {'form': SearchForm()}, context_instance=RequestContext(request))

def search(request):
    if 'number' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            return redirect(form.cleaned_data['ticket'])
        else:
            return render_to_response('tickets/search.html', {'form': form}, context_instance=RequestContext(request))
    else:
        return render_to_response('tickets/search.html', {'form': SearchForm()}, context_instance=RequestContext(request))

def number(request, number):
    ticket = get_object_or_404(Ticket, number=number)
    return redirect(ticket)

def voice(request):
    try:
        number = request.GET.get('number', None)
        if number is not None:
            ticket = Ticket.objects.get(number=number)
            response_text = ticket.status_detail
        else:
            response_text = "No ticket number specified"
    except Ticket.DoesNotExist:
        response_text = "Invalid ticket number"
    return HttpResponse(response_text)

def detail(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    return render_to_response('tickets/ticket.html', {
        'ticket': ticket,
        'show_history': settings.SHOW_HISTORY,
    }, context_instance=RequestContext(request))

templates/tickets/about.html
{% extends "tickets/base.html" %}

{% block content %}

<h1>About Frank&rsquo;s Electronics</h1>

<img class="photo" src="/static/images/van.jpg" alt="Frank's Electronics Van">

<p>Frank’s Electronics was actually opened as Frank’s Television on October
25, 1985, running out of a small Handi-house on the south side of town. Within
one year, the business grew to such an extent that I had to move to a bigger
location, and in February of 1987, I found a new location on North Main
Street.</p>

<p>With all of the extra room, I decided to branch out into car audio
installation but found the demand for TV repair so high that by 1990, I was
back to only servicing televisions and other electronics again and changed the
business name to Frank’s Electronics. Over the next few years, big-screen TVs
were all the rage so in 2006, I had to almost double my shop’s space to
accommodate the new trend. I now service all brands of TVs, including LCD,
LED, DLP, CRT, Plasma, and Rear-projection models.</p>

{% endblock %}

templates/tickets/base.html
{% load nav_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" xml:lang="en-US">
    <head>
        <meta http-equiv="Content-Type" content="text/html" />
        <title>{% block title %}Frank's Electronics{% endblock %}</title>
        <link rel="stylesheet" href="/static/css/reset.css" type="text/css" />
        <link rel="stylesheet" type="text/css" href="/static/css/base.css" />
        <link href='http://fonts.googleapis.com/css?family=Fondamento' rel='stylesheet' type='text/css' />
        <link href='http://fonts.googleapis.com/css?family=Amethysta' rel='stylesheet' type='text/css' />
        <link href='http://fonts.googleapis.com/css?family=Signika+Negative' rel='stylesheet' type='text/css' />
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        {% block extrahead %}
        {% endblock %}
    </head>

    <body>
        <div id="page">
            <div id="header">
                <a href="{% url tickets.views.index %}"><img src="/static/images/logo.png" alt="Frank's Electronics" /></a>
                <ul id="navlist">{% nav_list request %}</ul>
            </div>
        
            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

templates/tickets/index.html
{% extends "tickets/base.html" %}

{% block extrahead %}
<script type="text/javascript">
    $(document).ready(function () {
        $('#store-map-link').click(function () {
            $('#store-map-link').off('click');
            $('#store-map-link').html('View larger map on Google Maps');
            $('#store-map').toggle('show');
            $('#store-map').html('<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=306+North+Main+Street+Swainsboro,+Georgia+30401&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=40.460237,59.150391&amp;ie=UTF8&amp;hq=&amp;hnear=306+N+Main+St,+Swainsboro,+Georgia+30401&amp;t=m&amp;z=14&amp;ll=32.599734,-82.335984&amp;output=embed"></iframe>')
            return false;
        });
    });
</script>
{% endblock %}

{% block content %}

<p id="tagline">Swainsboro&rsquo;s place for electronics. Specializing in HD
TV service and repair, as well as digital HD antenna sales and
installation.</p>

<div class="info-group">
    <h2>CALL US</h2>
    <div class="info"><p>(478) 237-5176</p></div>
</div>

<div class="info-group">
    <h2>EMAIL US</h2>
    <div class="info" id="info-email">(enable JavaScript)</div>
</div>

<div class="info-group">
    <h2>OR STOP BY</h2>
    <div class="info">
        <p>306 North Main Street<br />
            Swainsboro, Georgia 30401</p>
        <p><a id="store-map-link" target="_new" href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=306+North+Main+Street+Swainsboro,+Georgia+30401&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=40.460237,59.150391&amp;ie=UTF8&amp;hq=&amp;hnear=306+N+Main+St,+Swainsboro,+Georgia+30401&amp;t=m&amp;z=14&amp;ll=32.599734,-82.335984">View map</a></p>
        <div id="store-map"></div>
    </div>
</div>

<div class="info-group">
    <h2>REPAIR STATUS</h2>
    <div class="info">
      {% include "tickets/search_form.html" %}
    </div>
</div>

<script type="text/javascript" src="/static/scripts/unobfuscate-email.js"></script>
<script type="text/javascript">
/* <![CDATA[ */
unobfuscateEmailAt('info-email', 'rFna@krFnasklEcertnociGs.Aocm');
/* ]]> */
</script>
{% endblock %}

templates/tickets/search.html
{% extends "tickets/base.html" %}
{% block content %}
<h1>Repair Status</h1>
{% include "tickets/search_form.html" %}
{% endblock %}

templates/tickets/search_form.html
<form action="{% url tickets.views.search %}" method="get">
<p>Enter a ticket number to check the status of your repair order.</p>
{{ form.as_p }}
<p><input type="submit" value="View Status" /></p>
</form>

templates/tickets/services.html
{% extends "tickets/base.html" %}

{% block content %}

<h1>Services</h1>

<p>Our service center consists of professional school-certified technicians.
We specialize in servicing and repair of high-definition projection big-screen
televisions, DLP projection televisions, LCD Projection televisions, and now
LCD, Plasma and LED flat-panel Televisions. Every unit gets a complete
professional disassembly, service and cleaning of all lenses and mirrors and
all cooling fans and wind tunnels for a longer lasting, clean, cooler, and
sharper picture. We also still service and repair DVD and VCR units and
install awesome HDTV antennas for a crisp, uncompressed high-definition
digital signal.</p>

<p>We are open from Monday through Friday 9AM to 5PM, and Saturday from 9AM
until noon. Please bring help for loading and unloading of TVs due to my
recent back condition. Thank you very much and I hope to see you soon.</p>

{% endblock %}

templates/tickets/ticket.html
{% extends "tickets/base.html" %}
{% block content %}
<h1>Repair Status</h1>
<div id="ticket-detail">
    <div id="ticket-number">
        <h3>Your ticket is</h3>
        <h2>#{{ ticket.number }}</h2>
    </div>

    <div class="ticket-field" id="ticket-make">
        <h2>Item make</h2>
        <p>{{ ticket.make }}&nbsp;</p>
    </div>

    <div class="ticket-field" id="ticket-model">
        <h2>Item model</h2>
        <p>{{ ticket.model }}&nbsp;</p>
    </div>

    <div class="ticket-field" id="ticket-status">
        <h2>Status</h2>
        <p>{{ ticket.get_status_display }}</p>
    </div>
    
    <div class="ticket-field" id="ticket-status-detail">
        <h2>Status detail</h2>
        <p>{{ ticket.status_detail }}&nbsp;</p>
    </div>
    
    <div class="ticket-field" id="ticket-notes">
        <h2>Notes</h2>
        <p>{{ ticket.notes }}</p>
    </div>
    
    <div class="ticket-row">

        <div class="ticket-field" id="ticket-estimate">
            <h2>Estimate amount</h2>
            <p>{{ ticket.estimate_display }}&nbsp;</p>
        </div>

        <div class="ticket-field" id="ticket-approved">
            <h2>Estimate approved?</h2>
            <p>{{ ticket.approved_display }}&nbsp;</p>
        </div>

    </div>

    <div class="ticket-row">

        <div class="ticket-field" id="ticket-estimate-date">
            <h2>Estimate completion date</h2>
            <p>{{ ticket.estimate_date_display }}&nbsp;</p>
        </div>

        <div class="ticket-field" id="ticket-approval-date">
            <h2>Estimate approval date</h2>
            <p>{{ ticket.approval_date_display }}&nbsp;</p>
        </div>

        <div class="ticket-field" id="ticket-completion-date">
            <h2>Repair completion date</h2>
            <p>{{ ticket.completion_date_display }}&nbsp;</p>
        </div>

    </div>

    {% if show_history %}
    <div class="ticket-field" id="ticket-history">
        <h2>Ticket history</h2>
        <ul>
        {% for status in ticket.statuslog_set.all %}
            <li>{{ status.timestamp }}: {{ status.get_status_display }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
{% endblock %}